name: Deploy via FTP (Locaweb)

on:
  push:
    branches:
      - main
    paths:
      - "html-version/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: FTP Deploy
        uses: locaweb/ftp-deploy@1.0.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: ./html-version/
          server-dir: /public_html/
